{"uid":"8642f57eef39db96","name":"test_save_as_reference_imageFile","fullName":"tests.test_previewApp_ImageComparison_SaveAs.TestImageComparisonSaveAs#test_save_as_reference_imageFile","historyId":"5093b2677ccabe9d6cb0bcfc8b12b51d","time":{"start":1729895809325,"stop":1729895818908,"duration":9583},"description":"Save the opened image as a reference image.","descriptionHtml":"<p>Save the opened image as a reference image.</p>\n","status":"broken","statusMessage":"FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.","statusTrace":"self = <test_previewApp_ImageComparison_SaveAs.TestImageComparisonSaveAs object at 0x107dbfbb0>\nbaseDir = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest'\n\n    @allure.step(\"Save the opened image as Reference Image\")\n    def test_save_as_reference_imageFile(self, baseDir):\n        \"\"\"Save the opened image as a reference image.\"\"\"\n    \n        file_path = os.path.join(baseDir, FIXTURES, SOURCE_IMAGES, REF_FILE_NAME)\n    \n        PreviewAppFunct.saveAsImage(REF_FILE_NAME)\n    \n        # ASSERT SAVE AS IMAGE IS EXIST\n>       PreviewAppFunct.assertcheckFileExists(file_path)\n\ntests/test_previewApp_ImageComparison_SaveAs.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfilepath = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png'\n\n    @staticmethod\n    def assertcheckFileExists(filepath):\n        \"\"\"Check if the specified file exists and raise an exception if not.\"\"\"\n        if not os.path.isfile(filepath):\n>           raise FileNotFoundError(f\"Error: The file '{filepath}' was not found.\")\nE           FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.\n\nglobals/functions/previewApp.py:118: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"test_tearDown","time":{"start":1729895784769,"stop":1729895784769,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"baseDir","time":{"start":1729895809325,"stop":1729895809325,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"testStage":{"description":"Save the opened image as a reference image.","status":"broken","statusMessage":"FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.","statusTrace":"self = <test_previewApp_ImageComparison_SaveAs.TestImageComparisonSaveAs object at 0x107dbfbb0>\nbaseDir = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest'\n\n    @allure.step(\"Save the opened image as Reference Image\")\n    def test_save_as_reference_imageFile(self, baseDir):\n        \"\"\"Save the opened image as a reference image.\"\"\"\n    \n        file_path = os.path.join(baseDir, FIXTURES, SOURCE_IMAGES, REF_FILE_NAME)\n    \n        PreviewAppFunct.saveAsImage(REF_FILE_NAME)\n    \n        # ASSERT SAVE AS IMAGE IS EXIST\n>       PreviewAppFunct.assertcheckFileExists(file_path)\n\ntests/test_previewApp_ImageComparison_SaveAs.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfilepath = '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png'\n\n    @staticmethod\n    def assertcheckFileExists(filepath):\n        \"\"\"Check if the specified file exists and raise an exception if not.\"\"\"\n        if not os.path.isfile(filepath):\n>           raise FileNotFoundError(f\"Error: The file '{filepath}' was not found.\")\nE           FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.\n\nglobals/functions/previewApp.py:118: FileNotFoundError","steps":[{"name":"Save the opened image as Reference Image","time":{"start":1729895809326,"stop":1729895818906,"duration":9580},"status":"broken","statusMessage":"FileNotFoundError: Error: The file '/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/fixtures/sourceImages/REF_Image.png' was not found.\n","statusTrace":"  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/tests/test_previewApp_ImageComparison_SaveAs.py\", line 48, in test_save_as_reference_imageFile\n    PreviewAppFunct.assertcheckFileExists(file_path)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest/globals/functions/previewApp.py\", line 118, in assertcheckFileExists\n    raise FileNotFoundError(f\"Error: The file '{filepath}' was not found.\")\n","steps":[],"attachments":[],"parameters":[{"name":"baseDir","value":"'/Users/runner/work/gui-chaos-pytest/gui-chaos-pytest'"}],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":1,"hasContent":true},"afterStages":[{"name":"test_tearDown::0","time":{"start":1729895818993,"stop":1729895819071,"duration":78},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"labels":[{"name":"suite","value":"Image Comparison Test with Preview App by SAVE AS Method"},{"name":"parentSuite","value":"tests"},{"name":"subSuite","value":"TestImageComparisonSaveAs"},{"name":"host","value":"Mac-1729894256472.local"},{"name":"thread","value":"3545-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_previewApp_ImageComparison_SaveAs"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"8642f57eef39db96.json","parameterValues":[]}